=== mscgenjs/mscgenjs-core/dist/cjs/parse/mscgenjs-ast.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "mscgenjs abstract syntax tree schema",
	"$ref": "#/definitions/SequenceChartType",
	"definitions": {
		"SequenceChartType": {
			"type": "object",
			"additionalProperties": false,
			"required": ["meta", "entities"],
			"properties": {
				"precomment": { "$ref": "#/definitions/PreCommentType" },
				"meta": { "$ref": "#/definitions/MetaType" },
				"options": { "$ref": "#/definitions/OptionsType" },
				"entities": {
					"type": "array",
					"items": { "$ref": "#/definitions/EntityType" }
				},
				"arcs": {
					"type": "array",
					"items": {
						"type": "array",
						"items": {
							"$ref": "#/definitions/ArcType"
						}
					}
				}
			}
		},
		"PreCommentType": {
			"description": "Comment preceding the sequence chart - potentially multi-line",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"MetaType": {
			"description": "Meta information about the chart",
			"type": "object",
			"additionalProperties": false,
			"required": ["extendedOptions", "extendedArcTypes", "extendedFeatures"],
			"properties": {
				"extendedOptions": {
					"description": "True if the chart uses non-mscgen ('extended') options",
					"type": "boolean",
					"default": false
				},
				"extendedArcTypes": {
					"description": "True if the chart uses non-mscgen arc types (e.g. composites, like 'loop' or 'alt')",
					"type": "boolean",
					"default": false
				},
				"extendedFeatures": {
					"description": "True any of the above is true",
					"type": "boolean",
					"default": false
				}
			}
		},
		"OptionsType": {
			"description": "Options that influence graphical rendition of the chart",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"hscale": {
					"description": "Horizontally scales the chart a bit. Numbers bigger than 1 enlarge it; smaller than 1 shrink it.",
					"type": "string"
				},
				"arcgradient": {
					"description": "With arcgradient all arcs get skewed a little",
					"type": "string"
				},
				"width": {
					"description": "Scales the whole chart so it fits in exactly the amount of pixels width. The special value \"auto\" auto-scales to 100% width in environments where this makes sense",
					"type": "string"
				},
				"wordwraparcs": {
					"description": "If true, text on arcs gets automatically wrapped",
					"type": "boolean"
				},
				"wordwrapentities": {
					"description": "If true, text in entities gets automatically wrapped",
					"type": "boolean"
				},
				"wordwrapboxes": {
					"description": "If true, text in boxes gets automatically wrapped",
					"type": "boolean"
				},
				"watermark": {
					"description": "Puts a watermark accross the chart",
					"type": "string"
				}
			}
		},
		"EntityType": {
			"description": "One of the entities between messages get passed",
			"type": "object",
			"additionalProperties": false,
			"required": ["name"],
			"properties": {
				"name": {
					"description": "The (unique) name of the entity",
					"type": "string"
				},
				"label": {
					"description": "Label to show for the entity",
					"type": "string"
				},
				"id": {
					"description": "",
					"type": "string"
				},
				"idurl": {
					"description": "",
					"type": "string"
				},
				"url": {
					"description": "",
					"type": "string"
				},
				"linecolor": {
					"description": "The color of the life line of the entity",
					"type": "string",
					"examples": [
						"red",
						"green",
						"transparent",
						"#fff",
						"#FFFFFF",
						"rgba(128, 128,1 128, 0.3)"
					]
				},
				"textcolor": {
					"description": "The color of the text",
					"type": "string"
				},
				"textbgcolor": {
					"description": "Background color of the entity",
					"type": "string"
				},
				"arclinecolor": {
					"description": "Line color for arcs departing from the lifeline of this entity",
					"type": "string"
				},
				"arctextcolor": {
					"description": "Text color for arcs departing from the lifeline of this entity",
					"type": "string"
				},
				"arctextbgcolor": {
					"description": "Text background color for arcs departing from the lifeline of this entity",
					"type": "string"
				},
				"arcskip": {
					"description": "(strictly possible as an attribute, but meaningless for entities)",
					"type": "string"
				},
				"title": {
					"description": "Text to show on hover (only functional on arcs a.t.m.)",
					"type": "string"
				},
				"activation": {
					"description": "Whether this arc activates (value=true) the target arc or de-activates (value=false) the source arc",
					"type": "boolean"
				}
			}
		},
		"ArcKindType": {
			"type": "string",
			"description": "All possible kinds of arcs",
			"enum": [
				"|||",
				"...",
				"---",
				"--",
				"<->",
				"==",
				"<=>",
				"<<=>>",
				"..",
				"<<>>",
				"::",
				"<:>",
				"->",
				"<-",
				"=>>",
				"<<=",
				"=>",
				"<=",
				">>",
				"<<",
				":>",
				"<:",
				"-x",
				"x-",
				"box",
				"note",
				"abox",
				"rbox",
				"alt",
				"else",
				"opt",
				"break",
				"par",
				"seq",
				"strict",
				"neg",
				"critical",
				"ignore",
				"consider",
				"assert",
				"loop",
				"ref",
				"exc"
			]
		},
		"ArcType": {
			"type": "object",
			"additionalProperties": false,
			"required": ["kind"],
			"properties": {
				"kind": {
					"description": "The kind of arc",
					"$ref": "#/definitions/ArcKindType",
					"examples": ["=>>", "->", "box", "note", "alt"]
				},
				"from": {
					"description": "(name of the) entity this arc is from",
					"type": "string"
				},
				"to": {
					"description": "(name of the) entity this arc goes to",
					"type": "string"
				},
				"arcs": {
					"oneOf": [
						{
							"type": "array",
							"items": {
								"type": "array",
								"items": {
									"$ref": "#/definitions/ArcType"
								}
							}
						},
						{
							"type": "null"
						}
					]
				},
				"label": {
					"description": "Label to show for the entity",
					"type": "string"
				},
				"id": {
					"description": "",
					"type": "string"
				},
				"idurl": {
					"description": "",
					"type": "string"
				},
				"url": {
					"description": "",
					"type": "string"
				},
				"linecolor": {
					"description": "The color of the line of the entity",
					"type": "string",
					"examples": [
						"red",
						"green",
						"transparent",
						"#fff",
						"#FFFFFF",
						"rgba(128, 128,1 128, 0.3)"
					]
				},
				"textcolor": {
					"description": "The color of the text",
					"type": "string"
				},
				"textbgcolor": {
					"description": "Background color of the text",
					"type": "string"
				},
				"arclinecolor": {
					"description": "(attribute is possible, but is meaningless for arcs)",
					"type": "string"
				},
				"arctextcolor": {
					"description": "(attribute is possible, but is meaningless for arcs)",
					"type": "string"
				},
				"arctextbgcolor": {
					"description": "(attribute is possible, but is meaningless for arcs)",
					"type": "string"
				},
				"arcskip": {
					"description": "The number of arcs to skip",
					"type": "string",
					"default": "0"
				},
				"title": {
					"description": "Text to show on hover (only functional on arcs a.t.m.)",
					"type": "string"
				},
				"activation": {
					"description": "Whether this arc activates (value=true) the target arc or de-activates (value=false) the source arc",
					"type": "boolean"
				}
			}
		}
	}
}

=== mscgenjs/mscgenjs-core/test/fixtures/arcskip/arcskip06.json
{
  "precomment": [
    "/*\n- two row arcskips, with the row it should point to having a height > normal\n */",
    "\n"
  ],
  "meta": {
    "extendedOptions": false,
    "extendedArcTypes": false,
    "extendedFeatures": false
  },
  "options": {
    "wordwraparcs": true
  },
  "entities": [
    {
      "name": "a"
    },
    {
      "name": "b"
    },
    {
      "name": "c"
    }
  ],
  "arcs": [
    [
      {
        "kind": "---"
      },
      {
        "kind": "->",
        "from": "a",
        "to": "b",
        "arcskip": "2",
        "label": "arcskip = 2"
      }
    ],
    [
      {
        "kind": "---"
      },
      {
        "kind": "->",
        "from": "b",
        "to": "c",
        "label": "arcskip is slower than this"
      }
    ],
    [
      {
        "kind": "---"
      },
      {
        "kind": "->",
        "from": "b",
        "to": "c",
        "label": "arcskip arc should connect to this (but it is heigher than the default height)"
      }
    ]
  ]
}

=== mscgenjs/mscgenjs-core/test/fixtures/astsimple.json
{
  "meta": {
    "extendedOptions": false,
    "extendedArcTypes": false,
    "extendedFeatures": false
  },
  "options": {
    "width": "300",
    "wordwraparcs": true
  },
  "entities": [
    {
      "name": "a"
    },
    {
      "name": "b space"
    },
    {
      "name": "c",
      "label": "aap noot mies wim zus jet\nteun vuur gijs lam kees bok"
    }
  ],
  "arcs": [
    [
      {
        "kind": "=>",
        "from": "a",
        "to": "b space",
        "label": "a simple script",
        "url": "http://github.com/sverweij/mscgen_js",
        "id": "1",
        "arcskip": "1"
      }
    ],
    [
      {
        "kind": "---",
        "linecolor": "green"
      }
    ],
    [
      {
        "kind": ":>",
        "from": "c",
        "to": "c",
        "label": "double your funk",
        "linecolor": "green"
      }
    ],
    [
      {
        "kind": "=>>",
        "from": "c",
        "to": "c",
        "label": "single file",
        "linecolor": "#123456"
      }
    ]
  ]
}

=== mscgenjs/mscgenjs-core/test/fixtures/bumpingboxes.json
{
  "precomment": [
    "# input to test that boxes running in parallel with inline expressions",
    "\n",
    "# do not bump into to them (and do not overlap)",
    "\n"
  ],
  "meta": {
    "extendedOptions": false,
    "extendedArcTypes": true,
    "extendedFeatures": true
  },
  "entities": [
    {
      "name": "a"
    },
    {
      "name": "b"
    }
  ],
  "arcs": [
    [
      {
        "kind": "box",
        "from": "a",
        "to": "a",
        "label": "Do cool stuff"
      },
      {
        "kind": "box",
        "from": "b",
        "to": "b",
        "label": "Do mundane stuff"
      }
    ],
    [
      {
        "kind": "alt",
        "from": "a",
        "to": "a",
        "arcs": [
          [
            {
              "kind": "box",
              "from": "a",
              "to": "a",
              "label": "Do cool stuff"
            },
            {
              "kind": "box",
              "from": "b",
              "to": "b",
              "label": "Do mundane stuff"
            }
          ]
        ],
        "label": "altbox"
      }
    ],
    [
      {
        "kind": "alt",
        "from": "b",
        "to": "b",
        "arcs": [
          [
            {
              "kind": "box",
              "from": "a",
              "to": "a",
              "label": "Do cool stuff"
            },
            {
              "kind": "box",
              "from": "b",
              "to": "b",
              "label": "Do mundane stuff"
            }
          ]
        ],
        "label": "altbox"
      }
    ]
  ]
}

=== mscgenjs/mscgenjs-core/test/fixtures/arcskip/arcskip03.json
{
  "precomment": [
    "/*\n * one row arcskips, with row height > normal row height; caused by current arc\n */",
    "\n"
  ],
  "meta": {
    "extendedOptions": false,
    "extendedArcTypes": false,
    "extendedFeatures": false
  },
  "options": {
    "wordwraparcs": true
  },
  "entities": [
    {
      "name": "a"
    },
    {
      "name": "b"
    },
    {
      "name": "c"
    }
  ],
  "arcs": [
    [
      {
        "kind": "---"
      },
      {
        "kind": "->",
        "from": "a",
        "to": "b",
        "arcskip": "1.5",
        "label": "arcskip = 1, this arc makes that the arc row height is heigher than the default archeight"
      }
    ],
    [
      {
        "kind": "---"
      },
      {
        "kind": "->",
        "from": "b",
        "to": "c",
        "label": "arcskip arc should connect to this"
      }
    ]
  ]
}

=== mscgenjs/mscgenjs-core/test/fixtures/arcskip/arcskip07.json
{
  "precomment": [
    "/*\n- 1/2 row arcskip, with a row height <= normal row height\n */",
    "\n"
  ],
  "meta": {
    "extendedOptions": false,
    "extendedArcTypes": false,
    "extendedFeatures": false
  },
  "options": {
    "wordwraparcs": true
  },
  "entities": [
    {
      "name": "a"
    },
    {
      "name": "b"
    },
    {
      "name": "c"
    }
  ],
  "arcs": [
    [
      {
        "kind": "---"
      },
      {
        "kind": "->",
        "from": "a",
        "to": "b",
        "arcskip": "0.5",
        "label": "arcskip = 0.5"
      }
    ],
    [
      {
        "kind": "---"
      },
      {
        "kind": "->",
        "from": "b",
        "to": "c",
        "label": "should land somewhere halfway above"
      }
    ]
  ]
}

=== mscgenjs/mscgenjs-core/test/fixtures/test10_stringsandurls.json
{
  "precomment": ["# test10 strings and \\\" & \\n escapes", "\n"],
  "meta": {
    "extendedOptions": false,
    "extendedArcTypes": false,
    "extendedFeatures": false
  },
  "options": {
    "hscale": "1.1"
  },
  "entities": [
    {
      "name": "a",
      "label": "\\\"Quoted\\\""
    },
    {
      "name": "b",
      "label": "line\\nbreak"
    },
    {
      "name": "c",
      "label": "No quotes"
    },
    {
      "name": "d",
      "id": "\\\"http://github.com\\\"",
      "idurl": "http://github.com"
    }
  ],
  "arcs": [
    [
      {
        "kind": "=>>",
        "from": "a",
        "to": "d",
        "label": "Just \\\"quotes\\\" and\\na linebreak, linking to mscgen_js on github",
        "url": "http://github.com/sverweij/mscgen_js",
        "id": "and an \\\"ID\\\" element linking\\nsomwhere else",
        "idurl": "http://home.kpn.nl/chromx/mscgen_js"
      }
    ],
    [
      {
        "kind": "=>>",
        "from": "c",
        "to": "d",
        "label": "no quotes"
      }
    ],
    [
      {
        "kind": ">>",
        "from": "d",
        "to": "a",
        "label": ""
      }
    ],
    [
      {
        "kind": "note",
        "from": "b",
        "to": "c",
        "label": "A box with a text and a\\n linebreak"
      }
    ],
    [
      {
        "kind": "|||"
      }
    ],
    [
      {
        "kind": "==",
        "from": "a",
        "to": "d",
        "label": "quote is in the ID",
        "id": "\\\"quoted, line\\nbrokenid\\\""
      }
    ],
    [
      {
        "kind": "=>>",
        "from": "a",
        "to": "b",
        "label": "\\nlinebreak at the start"
      },
      {
        "kind": "=>>",
        "from": "b",
        "to": "c",
        "label": "linebreak at the end\\n"
      }
    ],
    [
      {
        "kind": "|||",
        "label": "\\\"Explanation:\\\"\\nBlah and blah and bladee blah"
      }
    ]
  ]
}

=== mscgenjs/mscgenjs-core/test/fixtures/mirrorentities-off-regular-arc-last.json
{
  "precomment": ["# entities on bottom; regular arc last", "\n"],
  "meta": {
    "extendedOptions": true,
    "extendedArcTypes": false,
    "extendedFeatures": true
  },
  "entities": [
    {
      "name": "a"
    },
    {
      "name": "b"
    },
    {
      "name": "c"
    }
  ],
  "arcs": [
    [
      {
        "kind": "->",
        "from": "a",
        "to": "b"
      },
      {
        "kind": "note",
        "from": "c",
        "to": "c",
        "label": "entities on bottom; regular arc last"
      }
    ]
  ]
}

=== mscgenjs/mscgenjs-core/test/fixtures/arcskip/arcskip12.json
{
  "precomment": [
    "/*\n- one row arcskip accross an inline expression, with a row height <= normal row height\n */",
    "\n"
  ],
  "meta": {
    "extendedOptions": false,
    "extendedArcTypes": true,
    "extendedFeatures": true
  },
  "options": {
    "wordwraparcs": true
  },
  "entities": [
    {
      "name": "a"
    },
    {
      "name": "b"
    },
    {
      "name": "c"
    }
  ],
  "arcs": [
    [
      {
        "kind": "opt",
        "from": "a",
        "to": "c",
        "arcs": [
          [
            {
              "kind": "---"
            },
            {
              "kind": "->",
              "from": "a",
              "to": "b",
              "arcskip": "1",
              "label": "arcskip = 1"
            }
          ]
        ],
        "label": "optional all of this"
      }
    ],
    [
      {
        "kind": "---"
      },
      {
        "kind": "->",
        "from": "b",
        "to": "c",
        "label": "arcskip arc should connect to this"
      }
    ]
  ]
}
